### ISSUE TITLE
I can not see the code in Masek.cpp that Masek.h implemented.

### ISSUE THREAD

**Issue by world9604** [avilleret/NIST_VASIR#1]
Please help me. I would love to try this open source. I am a beginner in c ++. I would like to customize FindEyeLidCurve.cpp in this code. However, the Masek.h file is visible, but the Masek.cpp file is not visible.

**Comment by avilleret** [comment]
`Masek.cpp` is not visible because it doesn't exist at all.
as it is written in `Masek.h` : 

> This class gives all Masek methods a unified namespace

This is the only goal of this header. Function are *implemented* in separate `.cpp` files which are not called `Masek.cpp` which is not common I admit, but technically valid.

Although I'm not the author of this work, I just keep it there for convenience, please refer to https://www.nist.gov/services-resources/software/video-based-automatic-system-iris-recognition-vasir if you need help.
